---
# Name: staging/values.yaml
# Purpose: Staging environment Helm values for Jenkins wrapper chart configuration
# Description: Environment-specific overrides for staging deployment including
# image versioning, resource allocation, JVM optimization, and JCasC variables.
# Inherits base configuration from base/jenkins/values.yaml.
#
# persistence.size: Staging-appropriate storage allocation (4Gi)
# jenkins.controller.image: Staging image tag and pull policy optimization
# jenkins.controller.resources: Resource limits appropriate for staging workloads
# jenkins.controller.javaOpts: JVM tuning for staging memory constraints
# jenkins.controller.containerEnv: Environment variables for JCasC configuration
# jenkins.controller.ingress: External access configuration for staging environment

# Staging-specific persistence configuration
# Storage size configured in jenkins.persistence section below

# Jenkins subchart configuration overrides
# Inherits base configuration from: base/jenkins/values.yaml
jenkins:
  controller:
    # Container image configuration for staging environment
    # Uses specific commit SHA for staging validation
    # Pull policy optimized for staging (caching enabled)
    image:
      registry: "ghcr.io"
      repository: "lfit/jenkins"
      tag: "main-990a6cc"
      pullPolicy: "IfNotPresent"

    # Plugin management - use only plugins baked into image
    # Prevents plugin version conflicts in staging environment
    installPlugins: false

    # Resource allocation for staging environment
    # Lower resource limits appropriate for development/testing workloads
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"

    # JVM optimization for staging memory constraints
    # Memory settings aligned with resource limits above
    javaOpts: >-
      -XX:+UseG1GC
      -XX:+UseStringDeduplication
      -XX:+ParallelRefProcEnabled
      -XX:+DisableExplicitGC
      -Xmx1536m
      -XX:MaxMetaspaceSize=256m

    # Environment variables for Jenkins container (JCasC configuration)
    # Variables consumed by: base/jenkins/jcasc_yamls/ configuration files
    # Environment-specific values for staging deployment context
    containerEnv:
      # System Configuration (01-global-env-vars.yaml)
      - name: JCASC_SILO
        value: "staging"
      - name: JCASC_JENKINS_URL
        value: "https://jenkins-stag.opensearch.cluster.linuxfound.info/"
      - name: JENKINS_URL
        value: "https://jenkins-stag.opensearch.cluster.linuxfound.info/"
      - name: JCASC_LOCATION_URL
        value: ""
      - name: JCASC_LOCATION_ADMINADDRESS
        value: ""
      - name: JCASC_SYSTEM_MESSAGE
        value: "Welcome to Jenkins (Staging Environment)"
      - name: JCASC_MASTER_LABELS
        value: "staging-controller"
      - name: JCASC_RESOURCE_ROOT_URL
        value: ""

      # Build and Performance Configuration
      - name: JCASC_BUILD_TIMEOUT
        value: "3600"
      - name: JCASC_MAVEN_OPTS
        value: "-Xmx2048m -XX:MaxMetaspaceSize=512m"
      - name: JCASC_NODE_OPTIONS
        value: "--max-old-space-size=4096"
      - name: JCASC_SCM_POLLING_THREADCOUNT
        value: "5"

      # Integration Configuration (placeholders for future configuration)
      - name: JCASC_LOG_LEVEL
        value: "ERROR"
      - name: JCASC_ARTIFACTORY_URL
        value: ""
      - name: JCASC_DOCKER_REGISTRY
        value: ""
      - name: JCASC_S3_BUCKET
        value: ""
      - name: JCASC_CDN_URL
        value: ""
      - name: JCASC_ARTIFACTS_RETENTION_DAYS
        value: ""
      - name: JCASC_ECR_REGISTRY_URL
        value: ""

      # Security Configuration (02-security.yaml integration)
      - name: JCASC_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: jenkins-lf-admin
            key: admin-password

      # Kubernetes Cloud Configuration (07-cloud-agents.yaml integration)
      - name: JCASC_KUBERNETES_URL
        value: "https://kubernetes.default.svc.cluster.local"
      - name: JCASC_KUBERNETES_NAMESPACE
        value: "jenkins-staging"
      - name: JCASC_KUBERNETES_JENKINS_URL
        value: "http://jenkins-staging.jenkins-staging.svc.cluster.local:8080"
      - name: JCASC_KUBERNETES_JENKINS_TUNNEL
        value: "jenkins-staging-agent.jenkins-staging.svc.cluster.local:50000"

    # External access configuration for staging environment
    # Provides public access for development and testing workflows
    ingress:
      enabled: true
      apiVersion: networking.k8s.io/v1
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hostName: jenkins-stag.opensearch.cluster.linuxfound.info
      path: /
      tls:
        - secretName: jenkins-staging-tls
          hosts:
            - jenkins-stag.opensearch.cluster.linuxfound.info

  # Defining resource requests and limits for the staging environment.
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"

  jenkinsJavaOpts: "-Xms1g -Xmx2g"

  persistence:
    enabled: true
    storageClass: "auto-ebs-sc"
    size: "4Gi"
