# Name: staging/values.yaml
# Purpose: Provide Helm values customized for the Staging Jenkins env
# Description: Overrides Jenkins image, JVM opts, and JCasC env variables

jenkins:
  controller:
    image:
      registry: "ghcr.io"
      repository: "lfit/jenkins"
      tag: "main-6c30cda"
      pullPolicy: "IfNotPresent"

    # Override default plugins with empty list - use only image plugins
    installPlugins: false

    # Jenkins Configuration as Code - inherit from base values
    JCasC:
      defaultConfig: false

    # Environment variables for Jenkins container (JCasC configuration)
    containerEnv:
      - name: JCASC_SYSTEM_MESSAGE
        value: "Welcome to Jenkins (Staging Environment)"
      - name: JCASC_LOCATION_URL
        value: ""
      - name: JCASC_LOCATION_ADMINADDRESS
        value: "releng+opensearch-jenkins@linuxfoundation.org"
      - name: JCASC_MASTER_LABELS
        value: "staging-controller"
      - name: JCASC_RESOURCE_ROOT_URL
        value: ""
      - name: JCASC_DISABLE_DEFERRED_WIPEOUT
        value: "false"
      - name: JCASC_SCM_POLLING_THREADCOUNT
        value: "5"
      - name: JCASC_PROXY_HOST
        value: ""
      - name: JCASC_PROXY_PORT
        value: ""
      - name: JCASC_PROXY_USERNAME
        value: ""
      - name: JCASC_PROXY_NOPROXY
        value: ""
      - name: JCASC_FINGERPRINT_STORAGE
        value: ""
      - name: JCASC_FINGERPRINT_CLEANUP_PERIOD
        value: ""
      - name: JCASC_MAILER_SMTP_HOST
        value: ""
      - name: JCASC_MAILER_SMTP_PORT
        value: ""
      - name: JCASC_MAILER_USE_SSL
        value: "false"
      - name: JCASC_MAILER_USE_TLS
        value: "false"
      - name: JCASC_MAILER_SMTP_USERNAME
        value: ""
      - name: JCASC_MAILER_DEFAULT_SUFFIX
        value: ""
      - name: JCASC_MAILER_CHARSET
        value: "UTF-8"
      - name: JCASC_JENKINSGLOBALENVVARS_LOGLEVEL
        value: ""
      - name: JCASC_JENKINSGLOBALENVVARS_ARTIFACTORYURL
        value: ""
      - name: JCASC_JENKINSGLOBALENVVARS_DOCKERREGISTRY
        value: ""
      - name: JCASC_JENKINSGLOBALENVVARS_GITBASEURL
        value: ""
      - name: JCASC_JENKINSGLOBALENVVARS_GITURL
        value: ""
      - name: JCASC_JENKINSGLOBALENVVARS_PACKAGECLOUDPROXY
        value: ""
      - name: JCASC_JENKINSGLOBALENVVARS_PCIOCO
        value: ""
      - name: JCASC_JENKINSGLOBALENVVARS_RELEASEEMAIL
        value: ""
      - name: JCASC_JENKINSGLOBALENVVARS_RELEASEUSERNAME
        value: ""
      - name: JCASC_JENKINSGLOBALENVVARS_S3BUCKET
        value: ""
      - name: JCASC_JENKINSGLOBALENVVARS_CDNURL
        value: ""
      - name: JCASC_JENKINSGLOBALENVVARS_SIGULKEY
        value: ""
      - name: JCASC_JENKINSGLOBALENVVARS_SILO
        value: "staging"

      # Kubernetes Cloud Configuration
      - name: JCASC_KUBERNETES_NAMESPACE
        value: "jenkins-staging"
      - name: JCASC_KUBERNETES_JENKINS_URL
        value: "http://jenkins-staging.jenkins-staging.svc.cluster.local:8080"
      - name: JCASC_KUBERNETES_JENKINS_TUNNEL
        value: "jenkins-staging-agent.jenkins-staging.svc.cluster.local:50000"

    # Add ingress configuration for public access
    ingress:
      enabled: true
      apiVersion: networking.k8s.io/v1
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hostName: jenkins-stag.opensearch.cluster.linuxfound.info
      path: /
      tls:
        - secretName: jenkins-staging-tls
          hosts:
            - jenkins-stag.opensearch.cluster.linuxfound.info

  # Defining resource requests and limits for the staging environment.
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"

  jenkinsJavaOpts: "-Xms1g -Xmx2g"

  persistence:
    enabled: true
    storageClass: "auto-ebs-sc"
    size: "20Gi"
