# jcasc/02-security.yaml
---
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "{{ .Values.jenkinsSecurity.adminPassword | default \"{AQAAABAAAAAQplaceholderhash...}\" }}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
