# jcasc/02-security.yaml
# CSRF Protection: Prevents cross-site request forgery attacks
# NOTE: If automated scripts/API calls start failing with 403 errors,
# they may need to be updated to include CSRF tokens (crumbs)
---
jenkins:
  # Enable CSRF protection
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  # Disable "Remember me" functionality for better security
  # Users will need to re-authenticate after session expires
  disableRememberMe: true
  # SAML SSO Authentication via Linux Foundation SSO
  # Emergency Access: Use 02-security-emergency.yaml if LF SSO is down
  securityRealm:
    saml:
      binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
      displayNameAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
      emailAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
      groupsAttributeName: "http://schemas.xmlsoap.org/claims/Group"
      idpMetadataConfiguration:
        period: 60
        url: "${SAML_METADATA_URL}"
      logoutUrl: "${SAML_LOGOUT_URL}"
      maximumAuthenticationLifetime: 86400
      usernameCaseConversion: "none"
      usernameAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"
  authorizationStrategy:
    projectMatrix:
      permissions:
        # Admin users - full control (known LF staff)
        - "Overall/Administer:lf-jenkins"
        - "Overall/Administer:valderrv"
        - "Overall/Administer:rdetjens"
        # Standard authenticated users - limited permissions
        - "Overall/Read:authenticated"
        - "Job/Build:authenticated"
        - "Job/Cancel:authenticated"
        - "Job/Read:authenticated"
        - "Job/Workspace:authenticated"
        - "View/Read:authenticated"
