# jcasc/02-security.yaml
---
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: '${JCASC_ADMIN_PASSWORD}'
        - id: "lf-jenkins"
          password: '${JCASC_LFJENKINS_ADMINPASSWORD}'
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
