controller:
  initContainers:
    - name: jcasc-init
      image: jenkins-custom:latest
      command: ["/usr/share/jenkins/ref/bin/entrypoint.sh"]
      volumeMounts:
        - name: jcasc
          mountPath: /workspace/jcasc
    - name: plugin-init
      image: jenkins-custom:latest
      command: ["/bin/sh", "/usr/share/jenkins/ref/bin/plugin-entrypoint.sh"]
      volumeMounts:
        - name: plugin-config
          mountPath: /workspace/config
        - name: plugins
          mountPath: /workspace/plugins

  volumes:
    - name: jcasc
      emptyDir: {}
    - name: plugins
      emptyDir: {}
    - name: plugin-config
      configMap:
        name: jenkins-plugin-config-dev

  container:
    volumeMounts:
      - name: jcasc
        mountPath: /var/jenkins_home/casc_configs
      - name: plugins
        mountPath: /var/jenkins_home/plugins

  serviceAccount:
    create: true
