# Name: dev/values.yaml
# Purpose: Provide Helm values customized for the Development Jenkins env
# Description: Overrides Jenkins image, JVM opts, and JCasC env variables
# Fields:
#   controller.image.repository: Custom Jenkins image repository
#   controller.image.tag: Tag for the Jenkins image (e.g., "0.6-dev")
#   controller.image.pullPolicy: Image pull policy for Dev
#   jenkinsJavaOpts: JVM options for the Jenkins master
#   jenkinsEnvVars: JCASC_… env vars for JCasC configuration
# Usage:
#   1. Update controller.image.* for your Dev image requirements
#   2. Modify jenkinsJavaOpts to adjust JVM settings
#   3. Populate jenkinsEnvVars for Dev-specific JCASC variables
#   4. Open a PR; once merged, Argo CD will deploy the updates

controller:
  image:
    # TODO: Set to your local dev image or org image
    repository: ""
    tag: "0.6-dev"
    pullPolicy: "IfNotPresent"

jenkinsJavaOpts: "-Xms512m -Xmx1024m"

# Optional: Define resource requests and limits
# resources:
#   requests:
#     cpu: "500m"
#     memory: "1Gi"
#   limits:
#     cpu: "1"
#     memory: "2Gi"

jenkinsEnvVars:
  env:
  JCASC_LOG_LEVEL: "ERROR"
  JCASC_ARTIFACTORY_URL: ""
  JCASC_DOCKER_REGISTRY: ""
  JCASC_GIT_BASE: "https://github.com"
  JCASC_GIT_URL: "https://github.com"
  JCASC_S3_BUCKET: ""
  JCASC_CDN_URL: ""
  JCASC_LOCATION_URL: ""
  JCASC_LOCATION_ADMINADDRESS: "dev-admin@example.com"
  JCASC_MASTER_LABELS: "dev-master local"
  JCASC_RESOURCE_ROOT_URL: ""
  JCASC_DISABLE_DEFERRED_WIPEOUT: "false"
  JCASC_SCM_POLLING_THREADCOUNT: "5"
  JCASC_SILO: "development"
  JCASC_JENKINS_URL: ""
  JCASC_BUILD_TIMEOUT: ""
  JCASC_NODE_OPTIONS: ""
  JCASC_MAVEN_OPTS: ""
  JCASC_ARTIFACTS_RETENTION_DAYS: ""
  JCASC_ECR_REGISTRY_URL: ""
  JCASC_WORKFLOW_TEST: "pr-validation"

  # WARNING: Dev-only. Set this in your local env or via a Secret.
  JCASC_ADMIN_PASSWORD: ""
