apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lfit/jenkins-gitops
    targetRevision: HEAD
    path: base/jenkins
    helm:
      parameters:
        - name: serviceAccount.create
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
