apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-dev
  namespace: argocd
spec:
  project: jenkins
  source:
    repoURL: https://github.com/lfit/jenkins-gitops
    targetRevision: master
    path: base/jenkins
    helm:
      valueFiles:
        - ../../dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
