# Name: values.yaml
# Purpose: Default Helm values for the Jenkins wrapper chart
# Description: Sets PVC, service account, Jenkins image, and JCasC configuration

persistence:
  enabled: true
  size: 8Gi
  storageClass: "auto-ebs-sc"

serviceAccount:
  create: true
  name: ""

# Pass all configuration to Jenkins subchart
jenkins:
  controller:
    # Admin users managed via JCasC security configuration
    # See: base/jenkins/jcasc_yamls/02-security.yaml

    image:
      registry: "ghcr.io"
      repository: "lfit/jenkins"
      tag: "latest"
      pullPolicy: "IfNotPresent"

    # Use native chart fields instead of JCasC to avoid conflicts
    numExecutors: 0
    executorMode: EXCLUSIVE

    JCasC:
      defaultConfig: false
      configScripts:

        01-global-env-vars: |
          jenkins:
            globalNodeProperties:
            - envVars:
                env:
                - key: "GLOBAL_LOG_LEVEL"
                  value: '${JCASC_JENKINSGLOBALENVVARS_LOGLEVEL}'
                - key: "ARTIFACTORY_URL"
                  value: '${JCASC_JENKINSGLOBALENVVARS_ARTIFACTORYURL}'
                - key: "COMPANY_NAME"
                  value: "OpenSearch Project"
                - key: "DOCKER_REGISTRY"
                  value: '${JCASC_JENKINSGLOBALENVVARS_DOCKERREGISTRY}'
                - key: "GIT_BASE"
                  value: '${JCASC_JENKINSGLOBALENVVARS_GITBASEURL}/$PROJECT'
                - key: "GIT_URL"
                  value: '${JCASC_JENKINSGLOBALENVVARS_GITURL}'
                - key: "PACKAGECLOUDPROXY"
                  value: '${JCASC_JENKINSGLOBALENVVARS_PACKAGECLOUDPROXY}'
                - key: "PCIO_CO"
                  value: '${JCASC_JENKINSGLOBALENVVARS_PCIOCO}'
                - key: "RELEASE_EMAIL"
                  value: '${JCASC_JENKINSGLOBALENVVARS_RELEASEEMAIL}'
                - key: "RELEASE_USERNAME"
                  value: '${JCASC_JENKINSGLOBALENVVARS_RELEASEUSERNAME}'
                - key: "S3_BUCKET"
                  value: '${JCASC_JENKINSGLOBALENVVARS_S3BUCKET}'
                - key: "CDN_URL"
                  value: '${JCASC_JENKINSGLOBALENVVARS_CDNURL}'
                - key: "SIGUL_KEY"
                  value: '${JCASC_JENKINSGLOBALENVVARS_SIGULKEY}'
                - key: "SILO"
                  value: '${JCASC_JENKINSGLOBALENVVARS_SILO}'

        02-security: |
          jenkins:
            securityRealm:
              local:
                allowsSignup: false
                users:
                  - id: "lf-jenkins"
                    password: '${JCASC_LFJENKINS_ADMINPASSWORD}'
            authorizationStrategy:
              loggedInUsersCanDoAnything:
                allowAnonymousRead: false

        03-tools: |
          tool:
            jdk:
              installations:
                - name: "jdk-17"
                  home: "/opt/java/openjdk"
            git:
              installations:
                - name: "Default"
                  home: "git"

        04-global-libraries: |
          # Jenkins global pipeline library configurations placeholder

        05-plugins-config: |
          unclassified:
            gitHubConfiguration:
              apiRateLimitChecker: ThrottleForNormalize
            gitHubPluginConfig:
              configs:
                - name: "opensearch-project"
                  credentialsId: "github-api-token-placeholder"
              hookUrl: "http://jenkins.placeholder.example.com/github-webhook/"
            ghprbTrigger:
              cron: "H/5 * * * *"
              githubAuth:
                - id: "opensearch-project-ghprb-auth"
                  serverAPIUrl: "https://api.github.com"
                  credentialsId: "github-api-token-placeholder"
                  description: "GitHub auth for opensearch-project PR builder"
              adminlist: ""
              manageWebhooks: false
              okToTestPhrase: ".*ok to test.*"
              retestPhrase: ".*test this please.*"
              skipBuildPhrase: ".*\\[skip ci\\].*"

        06-credentials: |
          # Jenkins credential configurations placeholder

        07-cloud-agents: |
          # Cloud agents configuration moved to separate jcasc_yamls file
          # See: base/jenkins/jcasc_yamls/07-cloud-agents.yaml
