# Name: values.yaml
# Purpose: Default Helm values for the Jenkins wrapper chart
# Description: Sets PVC, service account, Jenkins image, and JCasC configuration

persistence:
  enabled: true
  size: 8Gi
  storageClass: "auto-ebs-sc"

serviceAccount:
  create: true
  name: ""

# Pass all configuration to Jenkins subchart
jenkins:
  controller:
    image:
      registry: "ghcr.io"
      repository: "lfit/jenkins"
      tag: "latest"
      pullPolicy: "IfNotPresent"

    JCasC:
      defaultConfig: true
