apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opensearch-jenkins-ec2-key
  namespace: {{ template "jenkins.namespace" . }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: onepassword-releng
  target:
    creationPolicy: Owner
  data:
    - secretKey: private-key
      remoteRef:
        key: "opensearch-jenkins-ec2-key/private key"
