---
name: Build InitContainer Image

"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-init:
    name: Build InitContainer Dockerfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build InitContainer image
        run: docker build -t initcontainer-test -f base/jenkins/init/Dockerfile .
