# Validates ArgoCD Application and AppProject manifests against their
# schema definitions.

name: Validate ArgoCD Schema

on:
  pull_request:
    paths:
      - 'argocd-apps/**/*.yaml'
      - 'argocd-apps/**/*.yml'
  push:
    branches:
      - main
    paths:
      - 'argocd-apps/**/*.yaml'
      - 'argocd-apps/**/*.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-schema:
    name: Validate ArgoCD Manifest Schemas
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Download kubeconform
        run: |
          set -euo pipefail
          curl -sSfLo /tmp/kubeconform.tar.gz \
            https://github.com/yannh/kubeconform/releases/download/v0.7.0/kubeconform-linux-amd64.tar.gz
          echo "c31518ddd122663b3f3aa874cfe8178cb0988de944f29c74a0b9260920d115d3  /tmp/kubeconform.tar.gz" | sha256sum -c
          tar -xzf /tmp/kubeconform.tar.gz -C /tmp
          chmod +x /tmp/kubeconform

      - name: Validate ArgoCD manifests
        run: |
          set -euo pipefail
          /tmp/kubeconform \
            -strict \
            -summary \
            -output text \
            -kubernetes-version 1.33.0 \
            -schema-location default \
            -schema-location 'https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.0/manifests/crds/{{.ResourceKind | lower}}-crd.yaml' \
            argocd-apps/
