---
# Helm values for Jenkins in the dev environment (local k3d cluster)
# This file enables JCasC, disables the default config, and prepares for external config injection.

# The 'controller' section configures the Jenkins controller behavior
controller:

  # List of plugins to pre-install.
  # Leave empty during scaffolding; will be populated later.
  installPlugins: []

  # Jenkins Configuration as Code (JCasC) settings
  JCasC:
    # Enable JCasC support in the Helm chart
    enabled: true

    # Disable default JCasC config provided by the chart
    defaultConfig: false

    # Placeholder for inline config scripts.
    # We rely on mounted files via InitContainer instead.
    configScripts: {}

  # Define shared volumes for InitContainer and Jenkins controller
  volumes:
    - name: jcasc
      emptyDir: {}

  # InitContainer to copy JCasC files into a shared volume
  initContainers:
    - name: jcasc-init
      image: alpine:3.18
      command: ["/entrypoint.sh"]
      volumeMounts:
        - name: jcasc
          mountPath: /workspace/jcasc
